---
title: "Untitled"
author: "D"
date: "08 agosto 2017"
output: html_document
---


## R example of EDA for Sepal Length in Iris dataset

Combines boxplots, beeswarm and stripchart plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

if(!require(datasets)) install.packages("datasets",repos = "http://cran.us.r-project.org")
if(!require(beeswarm)) install.packages("beeswarm",repos = "http://cran.us.r-project.org")
if(!require(ISLR)) install.packages("ISLR",repos = "http://cran.us.r-project.org")

```

```{r}
library(datasets)

dim(iris)
str(iris)

head(iris, 1)
tail(iris, 1)

summary(iris)

hist(iris$Sepal.Length, main = 'Sepal Length', xlab = 'cm')

library(beeswarm)
vertical = TRUE
stripchart(data = iris, Sepal.Length ~ Species, vertical = vertical, method = 'jitter', jitter = 0.2, cex = 1, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nstripchart', ylab = 'cm')
beeswarm(Sepal.Length ~ Species, data = iris, vertical = vertical, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm')
boxplot(data = iris, Sepal.Length ~ Species, horizontal = !(vertical), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm')

vertical = FALSE
stripchart(data = iris, Sepal.Length ~ Species, vertical = vertical, method = 'jitter', jitter = 0.2, cex = 1, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nstripchart', xlab = 'cm')
beeswarm(Sepal.Length ~ Species, data = iris, vertical = vertical, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nbeeswarm', xlab = 'cm')
boxplot(data = iris, Sepal.Length ~ Species, horizontal = !(vertical), main = 'Sepal.Length vs Species\nbeeswarm', xlab = 'cm')

```

```{r}
vertical = TRUE
boxplot(data = iris, Sepal.Length ~ Species, horizontal = !(vertical), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm', outline = FALSE)
beeswarm(Sepal.Length ~ Species, data = iris, vertical = vertical, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm', add = TRUE)

```

```{r}
vertical = FALSE
boxplot(data = iris, Sepal.Length ~ Species, horizontal = !(vertical), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm', outline = FALSE)
beeswarm(Sepal.Length ~ Species, data = iris, vertical = vertical, pch = 16, col = rainbow(8), main = 'Sepal.Length vs Species\nbeeswarm', ylab = 'cm', add = TRUE)

```

## Regression example: Wages dataset

```{r}
library(ISLR)
plot(x = Wage$age, y = Wage$wage, pch = 16, col='red')
hist(Wage$wage)
```

Build a linear regression model:
```{r}
lm_wage <- lm(wage ~ age, data = Wage)
unseen <- data.frame(age = 60)
str(unseen)
```
Predict wage for 60-year old worker:
```{r}
# Predict the wage for a 60-year old worker
predict(lm_wage, unseen)
```

## Classification example: Spam filtering

```{r}
rm(list = ls())
emails = read.csv("emails_small.csv")
plot(emails, pch = 16, col="red", main="Spam/Ham vs average number of capital letters")
```

Prediction function:
```{r}
# Inspect definition of spam_classifier()
spam_classifier <- function(x){
  prediction <- rep(NA, length(x)) # initialize prediction vector
  prediction[x > 4] <- 1
  prediction[x >= 3 & x <= 4] <- 0
  prediction[x >= 2.2 & x < 3] <- 1
  prediction[x >= 1.4 & x < 2.2] <- 0
  prediction[x > 1.25 & x < 1.4] <- 1
  prediction[x <= 1.25] <- 0
  return(prediction) # prediction is either 0 or 1
}
```

```{r}
# Apply the classifier to the avg_capital_seq column: spam_pred
spam_pred = spam_classifier(emails$avg_capital_seq)

# Compare spam_pred to emails$spam. Use ==
spam_pred == emails$spam
```

```{r}
emails$spam = as.factor(emails$spam)
str(emails)
plot(emails)
boxplot(emails, horizontal = TRUE)
```

## Regression example: Linkedin views for the next 3 days
```{r}
linkedin = c(5,  7,  4,  9, 11, 10, 14, 17, 13, 11, 18, 17, 21, 21, 24, 23, 28, 35, 21, 27, 23)
days = 1:21
plot(x = days, y = linkedin , pch = 16, col = 'red')

# Fit a linear model called on the linkedin views per day: linkedin_lm
linkedin_lm = lm(linkedin ~ days)
# Predict the number of views for the next three days: linkedin_pred
future_days <- data.frame(days = 22:24)
linkedin_pred <- predict(linkedin_lm, future_days)

# Plot historical data and predictions
plot(linkedin ~ days, xlim = c(1, 24), pch = 16)
points(22:24, linkedin_pred, pch = 16, col = "red")
```

